/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseSplatRouteImport } from './routes/browse.$'
import { Route as AdminShareTokenRouteImport } from './routes/admin/share.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSplatRoute = BrowseSplatRouteImport.update({
  id: '/browse/$',
  path: '/browse/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShareTokenRoute = AdminShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse/$': typeof BrowseSplatRoute
  '/admin/share/$token': typeof AdminShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse/$': typeof BrowseSplatRoute
  '/admin/share/$token': typeof AdminShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse/$': typeof BrowseSplatRoute
  '/admin/share/$token': typeof AdminShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/browse/$' | '/admin/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/browse/$' | '/admin/share/$token'
  id: '__root__' | '/' | '/admin' | '/browse/$' | '/admin/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseSplatRoute: typeof BrowseSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$': {
      id: '/browse/$'
      path: '/browse/$'
      fullPath: '/browse/$'
      preLoaderRoute: typeof BrowseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/share/$token': {
      id: '/admin/share/$token'
      path: '/share/$token'
      fullPath: '/admin/share/$token'
      preLoaderRoute: typeof AdminShareTokenRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminShareTokenRoute: typeof AdminShareTokenRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShareTokenRoute: AdminShareTokenRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseSplatRoute: BrowseSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
