<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903</WarningsNotAsErrors>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\BannedSymbols.txt" Link="BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mirality.FileProviders.InMemory" Version="6.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="*" />
    <PackageReference Include="TUnit" Version="*" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageReference Include="TUnit.AspNetCore" Version="1.63.0" />
    <PackageReference Include="TUnit.Mocks.Logging" Version="1.63.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImageShare\ImageShare.csproj" />
  </ItemGroup>

</Project>